# Generated by Django 4.1.3 on 2022-11-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_advocate_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
