# Generated by Django 4.1.3 on 2022-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
